[environments]
  [environments.development]
    name = "vmware-vault-backend"
    namespace = ""
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
